name: Terraform CSV Firewall Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Debug PAN-OS API Access
        run: |
          echo "Testing API access to PAN-OS..."
          curl -k "https://192.168.0.156/api/?type=version&key=${{ secrets.PANOS_API_KEY }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.9

      - name: Validate Duplicate Firewall Rules
        run: python3 scripts/validate_rules.py

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          TF_VAR_panos_api_key: ${{ secrets.PANOS_API_KEY }}
