name: Terraform CSV Firewall Deployment

on:
  push:
    paths:
      - 'rules.csv'
      - 'terraform/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_panos_api_key: ${{ secrets.PANOS_API_KEY }}
