name: CSV Firewall Rule Pipeline

on:
  push:
    paths:
      - 'rules.csv'
      - 'terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform CSV Apply
    runs-on: self-hosted

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug PAN-OS API Key
        run: |
          echo "Testing PAN-OS API connectivity..."
          curl -k "https://192.168.0.156/api/?type=version&key=${{ secrets.PANOS_API_KEY }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.9

      - name: Check Terraform version
        run: terraform version

      - name: Validate for duplicate firewall rules
        run: python3 ../scripts/validate_rules.py

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          TF_VAR_panos_api_key: ${{ secrets.PANOS_API_KEY }}
