name: Terraform CSV Firewall Deployment

on:
  push:
    paths:
      - 'rules.csv'
      - 'terraform/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Debug API access
      run: |
        echo "Testing curl to PAN-OS..."
        curl -k "https://192.168.0.156/api/?type=version&key=${{ secrets.PANOS_API_KEY }}"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.3.9

    - name: Terraform Init
      run: terraform init
   
    - name: Debug Secret Access
      run: echo "PANOS key length: ${#TF_VAR_panos_api_key}"
      env:
        TF_VAR_panos_api_key: ${{ secrets.PANOS_API_KEY }}

    - name: Terraform Plan
      run: terraform plan -input=false
      env:
        TF_VAR_panos_api_key: ${{ secrets.PANOS_API_KEY }}
